name: baseX
description: BaseX Running With Flutter 2.10.5

publish_to: "none"

version: 1.0.1+1

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^4.0.4
  huawei_hmsavailability: ^6.4.0+303
  flutter_hms_gms_checker: ^1.0.0
  device_info_plus: 3.2.4
  package_info_plus: ^1.4.2
  get: ^4.6.5
  firebase_core: 2.1.1
  firebase_messaging: 14.0.3
  flutter_local_notifications: ^9.4.0
  # http: ^0.13.4
  intl: ^0.17.0
  path_provider: ^2.0.11
  flutter_statusbarcolor_ns: ^0.4.0
  flutter_keyboard_visibility: ^5.3.0
  shared_preferences: ^2.0.13
  flutter_localizations:
    sdk: flutter
